on:
  pull_request:
    branches:
      - product
    types: [closed]

jobs:
  jenkins:
    if: github.event.pull_request.merged == true
    name: Product deployment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name : Install Dependencies
        run: npm install package.json
      - name: npm build
        run: npm run build
        
      - name: Clean Up
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_SSH_ID }}
          password: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
          script: |
            cd /var/www/html/autotag
            rm -rf *
            
      - name: Copy file to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: ./dist
          remote: /var/www/html/autotag
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_SSH_ID }}
          password: ${{ secrets.REMOTE_SSH_KEY }}
          port: ${{ secrets.REMOTE_SSH_PORT }}
